/* Generated from calibration_reports/output/gold_standard_gpt56_sol.json. */
/* The reference is provisional and requires clinical and terminology adjudication. */
export const FALL_GAME_SOURCE = {
  "version": "CAL-GOLD-PROVISIONAL-1.0",
  "status": "provisional",
  "sourceFile": "gold_standard_gpt56_sol.json",
  "policy": {
    "adjudicator": "GPT-5.6 Sol",
    "scope": "conceptos clínicos explícitos y normalizables en SNOMED CT",
    "numericInference": "no se derivan diagnósticos ni normalidad/anormalidad desde cifras aisladas",
    "ambiguity": "se omiten abreviaturas no resolubles sin contexto suficiente",
    "span": "fragmento mínimo informativo presente literalmente en el texto",
    "attributes": "polaridad, certeza, temporalidad y sujeto según contexto textual"
  }
} as const;

export const FALL_GAME_CASES = [
  {
    "id": "CAL_01__BASICO__AMB__AMB_OTHER_5625802",
    "label": "CAL-01 · Básico · Ambulatorio",
    "text": "FRC HTA DBT II\n TTO LOSARTAN 100 DIA\n TIPODE CIRUGIA FX DE RODILLA\n ECG RS, TARZ NORMAL\n TA 130/80\n SOPLO-\n RQ CLASE II",
    "concepts": [
      {
        "id": "CAL_01__BASICO__AMB__AMB_OTHER_5625802::1",
        "literal": "HTA",
        "start": 4,
        "end": 7,
        "term": "hipertensión arterial",
        "sctid": "38341003",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_01__BASICO__AMB__AMB_OTHER_5625802::2",
        "literal": "DBT II",
        "start": 8,
        "end": 14,
        "term": "diabetes mellitus tipo 2",
        "sctid": "44054006",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_01__BASICO__AMB__AMB_OTHER_5625802::3",
        "literal": "LOSARTAN 100",
        "start": 20,
        "end": 32,
        "term": "losartán potásico 100 mg comprimido oral",
        "sctid": "407784004",
        "cat": "Fármaco",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_01__BASICO__AMB__AMB_OTHER_5625802::4",
        "literal": "FX DE RODILLA",
        "start": 53,
        "end": 66,
        "term": "fractura de rodilla",
        "sctid": "878852003",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_01__BASICO__AMB__AMB_OTHER_5625802::5",
        "literal": "ECG",
        "start": 68,
        "end": 71,
        "term": "procedimiento electrocardiográfico",
        "sctid": "29303009",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_01__BASICO__AMB__AMB_OTHER_5625802::6",
        "literal": "RS, TARZ NORMAL",
        "start": 72,
        "end": 87,
        "term": "electrocardiograma: ritmo sinusal normal",
        "sctid": "426285000",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_01__BASICO__AMB__AMB_OTHER_5625802::7",
        "literal": "SOPLO",
        "start": 100,
        "end": 105,
        "term": "soplo cardíaco",
        "sctid": "88610006",
        "cat": "Hallazgo clínico",
        "pol": "Negado",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_01__BASICO__AMB__AMB_OTHER_5625802::8",
        "literal": "RQ CLASE II",
        "start": 108,
        "end": 119,
        "term": "con riesgo de complicación perioperatoria aumentado",
        "sctid": "457131000221101",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      }
    ]
  },
  {
    "id": "CAL_02__BASICO__AMB__AMB_OTHER_15795803",
    "label": "CAL-02 · Básico · Ambulatorio",
    "text": "paciente estable sin productividad psicotica aguda ni ideacion auto o heterolitica al moent del examen \np de alarma \nrisperidona 1 mg 1 1 2 \nquetiapina 100 mg  - -  1\nlic marisa gallardo ",
    "concepts": [
      {
        "id": "CAL_02__BASICO__AMB__AMB_OTHER_15795803::1",
        "literal": "paciente estable",
        "start": 0,
        "end": 16,
        "term": "paciente estable",
        "sctid": "359746009",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_02__BASICO__AMB__AMB_OTHER_15795803::2",
        "literal": "productividad psicotica aguda",
        "start": 21,
        "end": 50,
        "term": "psicosis aguda",
        "sctid": "65971000052100",
        "cat": "Hallazgo clínico",
        "pol": "Negado",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_02__BASICO__AMB__AMB_OTHER_15795803::3",
        "literal": "ideacion auto",
        "start": 54,
        "end": 67,
        "term": "ideación suicida",
        "sctid": "6471006",
        "cat": "Hallazgo clínico",
        "pol": "Negado",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_02__BASICO__AMB__AMB_OTHER_15795803::4",
        "literal": "heterolitica",
        "start": 70,
        "end": 82,
        "term": "pensamientos de homicidio",
        "sctid": "225450009",
        "cat": "Hallazgo clínico",
        "pol": "Negado",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_02__BASICO__AMB__AMB_OTHER_15795803::5",
        "literal": "risperidona 1 mg",
        "start": 117,
        "end": 133,
        "term": "risperidona 1 mg comprimido oral",
        "sctid": "321589009",
        "cat": "Fármaco",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_02__BASICO__AMB__AMB_OTHER_15795803::6",
        "literal": "quetiapina 100 mg",
        "start": 141,
        "end": 158,
        "term": "quetiapina (como fumarato de quetiapina) 100 mg comprimido oral",
        "sctid": "321625005",
        "cat": "Fármaco",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      }
    ]
  },
  {
    "id": "CAL_03__BASICO__AMB__AMB_OTHER_8377206",
    "label": "CAL-03 · Básico · Ambulatorio",
    "text": "ENOLISTA CRONICO SEVERO,MARIHUANA,COCAINA ESPORADICA.CONSUMO DESDE JOVEN. hIGADO: ESTEATOSIS LEVE A MODERADA. iNTERCURRE CON 3 EPISODIOS CONVULSIVOS.PIDO TAC ENCEFALO + EEG,LUEGO VER ECODOPPLER!!!!",
    "concepts": [
      {
        "id": "CAL_03__BASICO__AMB__AMB_OTHER_8377206::1",
        "literal": "ENOLISTA CRONICO SEVERO",
        "start": 0,
        "end": 23,
        "term": "alcoholismo crónico continuo",
        "sctid": "191811004",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_03__BASICO__AMB__AMB_OTHER_8377206::2",
        "literal": "MARIHUANA",
        "start": 24,
        "end": 33,
        "term": "usuario de marihuana",
        "sctid": "733460004",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_03__BASICO__AMB__AMB_OTHER_8377206::3",
        "literal": "COCAINA ESPORADICA",
        "start": 34,
        "end": 52,
        "term": "consumidor de cocaína",
        "sctid": "733461000",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_03__BASICO__AMB__AMB_OTHER_8377206::4",
        "literal": "ESTEATOSIS LEVE A MODERADA",
        "start": 82,
        "end": 108,
        "term": "esteatosis hepática",
        "sctid": "197321007",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_03__BASICO__AMB__AMB_OTHER_8377206::5",
        "literal": "3 EPISODIOS CONVULSIVOS",
        "start": 125,
        "end": 148,
        "term": "convulsión",
        "sctid": "91175000",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_03__BASICO__AMB__AMB_OTHER_8377206::6",
        "literal": "TAC ENCEFALO",
        "start": 154,
        "end": 166,
        "term": "TC de cerebro",
        "sctid": "34227000",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_03__BASICO__AMB__AMB_OTHER_8377206::7",
        "literal": "EEG",
        "start": 169,
        "end": 172,
        "term": "electroencefalograma",
        "sctid": "54550000",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_03__BASICO__AMB__AMB_OTHER_8377206::8",
        "literal": "ECODOPPLER",
        "start": 183,
        "end": 193,
        "term": "ecografía Doppler",
        "sctid": "1187106001",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      }
    ]
  },
  {
    "id": "CAL_04__BASICO__INT__INT_PHYSICAL_EXAM_16767364",
    "label": "CAL-04 · Básico · Internación",
    "text": "PACIENTE EN MAL ESTADO GENERAL. AFEBRIL T 36 TA 80/50 FC 100 FR 20 SPO2 93% CON OXIGENOTERAPIA A 3 L POR CANULA NASAL, MALA MECANICA RESPIRATORIA, QUEJOSA. ",
    "concepts": [
      {
        "id": "CAL_04__BASICO__INT__INT_PHYSICAL_EXAM_16767364::1",
        "literal": "MAL ESTADO GENERAL",
        "start": 12,
        "end": 30,
        "term": "estado de salud general malo",
        "sctid": "213257006",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_04__BASICO__INT__INT_PHYSICAL_EXAM_16767364::2",
        "literal": "AFEBRIL",
        "start": 32,
        "end": 39,
        "term": "fiebre",
        "sctid": "386661006",
        "cat": "Hallazgo clínico",
        "pol": "Negado",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_04__BASICO__INT__INT_PHYSICAL_EXAM_16767364::3",
        "literal": "OXIGENOTERAPIA A 3 L POR CANULA NASAL",
        "start": 80,
        "end": 117,
        "term": "oxigenoterapia intranasal",
        "sctid": "71786000",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_04__BASICO__INT__INT_PHYSICAL_EXAM_16767364::4",
        "literal": "MALA MECANICA RESPIRATORIA",
        "start": 119,
        "end": 145,
        "term": "respiración anormal",
        "sctid": "386813002",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_04__BASICO__INT__INT_PHYSICAL_EXAM_16767364::5",
        "literal": "QUEJOSA",
        "start": 147,
        "end": 154,
        "term": "quejido respiratorio",
        "sctid": "248623001",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      }
    ]
  },
  {
    "id": "CAL_05__BASICO__INT__INT_EVOLUTION_27022784",
    "label": "CAL-05 · Básico · Internación",
    "text": "Pte lúcido. Buena ingesta vo. AVP en MSD PHP a 35 gts x min+ ATB. Presenta SNG clampeada.Drenaje asp. débito(-) No refiere nauseas. VIsitado por familia. ",
    "concepts": [
      {
        "id": "CAL_05__BASICO__INT__INT_EVOLUTION_27022784::1",
        "literal": "Pte lúcido",
        "start": 0,
        "end": 10,
        "term": "lúcido",
        "sctid": "285241002",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_05__BASICO__INT__INT_EVOLUTION_27022784::2",
        "literal": "Buena ingesta vo",
        "start": 12,
        "end": 28,
        "term": "tolera la dieta",
        "sctid": "1144522003",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_05__BASICO__INT__INT_EVOLUTION_27022784::3",
        "literal": "AVP en MSD",
        "start": 30,
        "end": 40,
        "term": "acceso venoso permeable",
        "sctid": "448094004",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_05__BASICO__INT__INT_EVOLUTION_27022784::4",
        "literal": "PHP a 35 gts x min",
        "start": 41,
        "end": 59,
        "term": "tratamiento de rehidratación parenteral",
        "sctid": "243223007",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_05__BASICO__INT__INT_EVOLUTION_27022784::5",
        "literal": "ATB",
        "start": 61,
        "end": 64,
        "term": "tratamiento con antibióticos",
        "sctid": "281789004",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_05__BASICO__INT__INT_EVOLUTION_27022784::6",
        "literal": "SNG clampeada",
        "start": 75,
        "end": 88,
        "term": "cierre de sonda nasogástrica con tapón en espiga",
        "sctid": "225077009",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_05__BASICO__INT__INT_EVOLUTION_27022784::7",
        "literal": "Drenaje asp",
        "start": 89,
        "end": 100,
        "term": "drenaje por aspiración",
        "sctid": "274441001",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_05__BASICO__INT__INT_EVOLUTION_27022784::8",
        "literal": "débito(-)",
        "start": 102,
        "end": 111,
        "term": "egresos de líquidos por drenaje - hallazgo",
        "sctid": "366368001",
        "cat": "Hallazgo clínico",
        "pol": "Negado",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_05__BASICO__INT__INT_EVOLUTION_27022784::9",
        "literal": "No refiere nauseas",
        "start": 112,
        "end": 130,
        "term": "náuseas",
        "sctid": "422587007",
        "cat": "Hallazgo clínico",
        "pol": "Negado",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      }
    ]
  },
  {
    "id": "CAL_06__AVANZADO__AMB__AMB_OTHER_19518261",
    "label": "CAL-06 · Avanzado · Ambulatorio",
    "text": "Se comienza con evaluación psicopedagógica.\nPrimer encuentro con el niño, conversamos sobre sus gustos: actividades que le gusta hacer, juegos, amigos, colegio, familia, entre otros. Entra sin dificultad al consultorio, logra entablar diálogos desde el comienzo. Se realiza prueba proyectiva: Dibujo Libre. A partir de esta técnica se observa lo siguiente:\n-adecuado agarre del lápiz. Diestro\n-Trazo intenso, aprieta fuertemente el lápiz que termina rompiendo la punta.\n-Colorea adecuadamente, respetando las líneas y de manera prolija. Minucioso y detallista. \n",
    "concepts": [
      {
        "id": "CAL_06__AVANZADO__AMB__AMB_OTHER_19518261::1",
        "literal": "evaluación psicopedagógica",
        "start": 16,
        "end": 42,
        "term": "evaluación del aprendizaje",
        "sctid": "371586004",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_06__AVANZADO__AMB__AMB_OTHER_19518261::2",
        "literal": "prueba proyectiva: Dibujo Libre",
        "start": 274,
        "end": 305,
        "term": "pruebas proyectivas",
        "sctid": "165177008",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_06__AVANZADO__AMB__AMB_OTHER_19518261::3",
        "literal": "logra entablar diálogos",
        "start": 220,
        "end": 243,
        "term": "capaz de entablar conversación",
        "sctid": "288634004",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_06__AVANZADO__AMB__AMB_OTHER_19518261::4",
        "literal": "adecuado agarre del lápiz",
        "start": 358,
        "end": 383,
        "term": "capaz de agarrar",
        "sctid": "284257006",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_06__AVANZADO__AMB__AMB_OTHER_19518261::5",
        "literal": "Diestro",
        "start": 385,
        "end": 392,
        "term": "preferencia de mano derecha",
        "sctid": "299721003",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      }
    ]
  },
  {
    "id": "CAL_07__AVANZADO__AMB__AMB_OTHER_5180702",
    "label": "CAL-07 · Avanzado · Ambulatorio",
    "text": "Paciente de 9 años que ayer consultó a guardia por vomitos y dolor abdominal , le indicaron que si no mejoraba cosute. Persiste con vomitos y dolor abdominal . BEG afebril fauces s/p normihidratadacompensada hemodinamicamnete BEAB eupneica , abdomen blando depresible levemente doloroso a la palpación periumbilical no impresiona que duela ni defienda en FID rha+ Derivo a guardia de pediatria del htal para evaluación y alpicacion de reliveran im , solicito ecografia abdominal  . explico a la madre qe debe ir a la brevedad a la guardia , la madre manifiesta comprender . ",
    "concepts": [
      {
        "id": "CAL_07__AVANZADO__AMB__AMB_OTHER_5180702::1",
        "literal": "Persiste con vomitos",
        "start": 119,
        "end": 139,
        "term": "vómitos persistentes",
        "sctid": "196746003",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_07__AVANZADO__AMB__AMB_OTHER_5180702::2",
        "literal": "dolor abdominal",
        "start": 61,
        "end": 76,
        "term": "dolor abdominal",
        "sctid": "21522001",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_07__AVANZADO__AMB__AMB_OTHER_5180702::3",
        "literal": "BEG",
        "start": 160,
        "end": 163,
        "term": "estado general de salud, bueno",
        "sctid": "135815002",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_07__AVANZADO__AMB__AMB_OTHER_5180702::4",
        "literal": "afebril",
        "start": 164,
        "end": 171,
        "term": "fiebre",
        "sctid": "386661006",
        "cat": "Hallazgo clínico",
        "pol": "Negado",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_07__AVANZADO__AMB__AMB_OTHER_5180702::5",
        "literal": "normihidratada",
        "start": 183,
        "end": 197,
        "term": "adecuadamente hidratado",
        "sctid": "1144674006",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_07__AVANZADO__AMB__AMB_OTHER_5180702::6",
        "literal": "compensada hemodinamicamnete",
        "start": 197,
        "end": 225,
        "term": "hemodinámicamente estable",
        "sctid": "301459008",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_07__AVANZADO__AMB__AMB_OTHER_5180702::7",
        "literal": "abdomen blando",
        "start": 242,
        "end": 256,
        "term": "abdomen blando",
        "sctid": "249543005",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_07__AVANZADO__AMB__AMB_OTHER_5180702::8",
        "literal": "doloroso a la palpación periumbilical",
        "start": 278,
        "end": 315,
        "term": "dolor a la palpación de la región periumbilical",
        "sctid": "445386003",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_07__AVANZADO__AMB__AMB_OTHER_5180702::9",
        "literal": "no impresiona que duela ni defienda en FID",
        "start": 316,
        "end": 358,
        "term": "dolor en fosa ilíaca derecha",
        "sctid": "162051008",
        "cat": "Hallazgo clínico",
        "pol": "Negado",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_07__AVANZADO__AMB__AMB_OTHER_5180702::10",
        "literal": "ecografia abdominal",
        "start": 459,
        "end": 478,
        "term": "ecografía de abdomen",
        "sctid": "45036003",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      }
    ]
  },
  {
    "id": "CAL_08__AVANZADO__INT__INT_EVOLUTION_30442034",
    "label": "CAL-08 · Avanzado · Internación",
    "text": "- PACIENTE LUCIDA, REFIERE DOLOR, CON TENDENCIA A LA HIPERTENSION, SE LE AVISA A LOS MEDICOS CLINICOS Y OBSERVAN AL PACIENTE, INDICANDO PASAR AMLODIPINA 5 MG POR K 108.\n- INDICACION DE 18.00 PM/ INDICAN COLOCAR SONDA NASOGRASTRICA Y QUEDA COLOCA Y CORBORADO POR MEDICOS CLINICOS Y DAMOS INICIO A/E POR BIC + 250 AGUA POR TURNO.\n- CONTROLADO LOS SIGNOS VITALES Y MONITOREADO.\n- ACCESO VENOSO PERIFERICO INFUNDIENDO PHP DE SOLUCION FISIOLOGICO S/A.\n-  ADMINISTRA MEDICAMENTOS SEGUN INDICACION MEDICA EV ATB, VO K108, SC.\n- DIURESIS EN PAÑAL, HIGENIZADA Y SE ACONDICIONADA.\n",
    "concepts": [
      {
        "id": "CAL_08__AVANZADO__INT__INT_EVOLUTION_30442034::1",
        "literal": "PACIENTE LUCIDA",
        "start": 2,
        "end": 17,
        "term": "lúcido",
        "sctid": "285241002",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_08__AVANZADO__INT__INT_EVOLUTION_30442034::2",
        "literal": "REFIERE DOLOR",
        "start": 19,
        "end": 32,
        "term": "dolor",
        "sctid": "22253000",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_08__AVANZADO__INT__INT_EVOLUTION_30442034::3",
        "literal": "TENDENCIA A LA HIPERTENSION",
        "start": 38,
        "end": 65,
        "term": "hipertensión arterial",
        "sctid": "38341003",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_08__AVANZADO__INT__INT_EVOLUTION_30442034::4",
        "literal": "AMLODIPINA 5 MG",
        "start": 142,
        "end": 157,
        "term": "amlodipino (como besilato de amlodipino) 5 mg comprimido oral",
        "sctid": "783049000",
        "cat": "Fármaco",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_08__AVANZADO__INT__INT_EVOLUTION_30442034::5",
        "literal": "COLOCAR SONDA NASOGRASTRICA",
        "start": 203,
        "end": 230,
        "term": "colocación de una sonda nasogástrica",
        "sctid": "87750000",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_08__AVANZADO__INT__INT_EVOLUTION_30442034::6",
        "literal": "A/E POR BIC",
        "start": 294,
        "end": 305,
        "term": "alimentación enteral",
        "sctid": "229912004",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_08__AVANZADO__INT__INT_EVOLUTION_30442034::7",
        "literal": "CONTROLADO LOS SIGNOS VITALES",
        "start": 330,
        "end": 359,
        "term": "toma de signos vitales del paciente",
        "sctid": "61746007",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_08__AVANZADO__INT__INT_EVOLUTION_30442034::8",
        "literal": "ACCESO VENOSO PERIFERICO",
        "start": 377,
        "end": 401,
        "term": "acceso venoso permeable",
        "sctid": "448094004",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_08__AVANZADO__INT__INT_EVOLUTION_30442034::9",
        "literal": "INFUNDIENDO PHP DE SOLUCION FISIOLOGICO",
        "start": 402,
        "end": 441,
        "term": "infusión continua de solución salina normal",
        "sctid": "313418004",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_08__AVANZADO__INT__INT_EVOLUTION_30442034::10",
        "literal": "EV ATB",
        "start": 498,
        "end": 504,
        "term": "tratamiento con antibióticos intravenosos",
        "sctid": "281790008",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      }
    ]
  },
  {
    "id": "CAL_09__AVANZADO__INT__INT_EVOLUTION_33078485",
    "label": "CAL-09 · Avanzado · Internación",
    "text": "12:00hs Se recibe laboratorio por planta que informa Hto34, Hb 10.1, GB 7, plaq 273, GOT 54, GPT 26, FAL 256, BT 0.1, crear 0.62, urea 22, ac úrico 6.3, LDH 243, TP 11, CP 0.48, KPTT 22, RIN 0.78, Na 136, K 4, Cl 104, proteinuria 19.1, creatininuria 74, indice proteinuria/ creatininuria 0.25. Se indica ferroterapia via oral.\n12:30hs Se brinda consejeria en anticoncepción, paciente opta por implante subdérmico (etonorgestrel 68mg) el cual se coloca según técnica.",
    "concepts": [
      {
        "id": "CAL_09__AVANZADO__INT__INT_EVOLUTION_33078485::1",
        "literal": "ferroterapia via oral",
        "start": 304,
        "end": 325,
        "term": "producto con hierro para administración oral",
        "sctid": "13790009",
        "cat": "Fármaco",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_09__AVANZADO__INT__INT_EVOLUTION_33078485::2",
        "literal": "consejeria en anticoncepción",
        "start": 345,
        "end": 373,
        "term": "asesoramiento para anticoncepción",
        "sctid": "72531000052105",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_09__AVANZADO__INT__INT_EVOLUTION_33078485::3",
        "literal": "implante subdérmico (etonorgestrel 68mg)",
        "start": 393,
        "end": 433,
        "term": "etonogestrel 68 mg implante subcutáneo de liberación prolongada",
        "sctid": "785088001",
        "cat": "Fármaco",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_09__AVANZADO__INT__INT_EVOLUTION_33078485::4",
        "literal": "el cual se coloca según técnica",
        "start": 434,
        "end": 465,
        "term": "inserción de implante de etonogestrel",
        "sctid": "438455008",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      }
    ]
  },
  {
    "id": "CAL_10__AVANZADO__INT__INT_EVOLUTION_27048196",
    "label": "CAL-10 · Avanzado · Internación",
    "text": "GUARDIA DE 06 a 18HS\nCAMA 2 PEREZ: PTE conectado MNI, en ARM ,con AVC + PHP + BIC MDZ+ BIC FNT + SNG con alimentación enteral + SV permeable.  Se  realiza TTO médico indicado, controles de hgt y ATB  por horario, se extrajo muestra para laboratorio y gasometria arterial.Normotenso, normocardico, afebril, buena spo2, eupneico, bien adaptado a parametros ventilatorios, es asistido por servicio de kinesiología, recibe visitas en horarios pautados, csv + diuresi(+), catarsis(-) +balance hídrico volcados en hoja de enfermería formato papel.\n",
    "concepts": [
      {
        "id": "CAL_10__AVANZADO__INT__INT_EVOLUTION_27048196::1",
        "literal": "ARM",
        "start": 57,
        "end": 60,
        "term": "ventilación mecánica invasiva",
        "sctid": "1258985005",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_10__AVANZADO__INT__INT_EVOLUTION_27048196::2",
        "literal": "AVC",
        "start": 66,
        "end": 69,
        "term": "catéter venoso central in situ",
        "sctid": "449239005",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_10__AVANZADO__INT__INT_EVOLUTION_27048196::3",
        "literal": "PHP",
        "start": 72,
        "end": 75,
        "term": "administración de líquidos intravenosos",
        "sctid": "103744005",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_10__AVANZADO__INT__INT_EVOLUTION_27048196::4",
        "literal": "BIC MDZ",
        "start": 78,
        "end": 85,
        "term": "producto con midazolam para administración parenteral",
        "sctid": "389105002",
        "cat": "Fármaco",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_10__AVANZADO__INT__INT_EVOLUTION_27048196::5",
        "literal": "BIC FNT",
        "start": 87,
        "end": 94,
        "term": "producto con fentanilo para administración parenteral",
        "sctid": "772460001",
        "cat": "Fármaco",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_10__AVANZADO__INT__INT_EVOLUTION_27048196::6",
        "literal": "SNG con alimentación enteral",
        "start": 97,
        "end": 125,
        "term": "alimentación por sonda nasogástrica",
        "sctid": "229914003",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_10__AVANZADO__INT__INT_EVOLUTION_27048196::7",
        "literal": "SV permeable",
        "start": 128,
        "end": 140,
        "term": "sonda urinaria uretral in situ",
        "sctid": "723542006",
        "cat": "Hallazgo clínico",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_10__AVANZADO__INT__INT_EVOLUTION_27048196::8",
        "literal": "controles de hgt",
        "start": 176,
        "end": 192,
        "term": "control de glucemia",
        "sctid": "698472009",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_10__AVANZADO__INT__INT_EVOLUTION_27048196::9",
        "literal": "gasometria arterial",
        "start": 251,
        "end": 270,
        "term": "medición arterial de gases en sangre",
        "sctid": "91308007",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      },
      {
        "id": "CAL_10__AVANZADO__INT__INT_EVOLUTION_27048196::10",
        "literal": "asistido por servicio de kinesiología",
        "start": 373,
        "end": 410,
        "term": "sesión de kinesiología",
        "sctid": "552861000221107",
        "cat": "Procedimiento",
        "pol": "Activo",
        "cert": "Confirmado",
        "temp": "Actual",
        "suj": "Paciente"
      }
    ]
  }
] as const;
